In [2]:
!pip install sastrawi

Collecting sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 5.1 MB/s eta 0:00:0000:01
Installing collected packages: sastrawi
Successfully installed sastrawi-1.0.1

## Load & cek data awal

In [3]:
import pandas as pd
import re
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

path = "/kaggle/input/notebooks/mengkoding47/crawling-ferischa/detik_random_1260.csv"
df = pd.read_csv(path)

print("Data awal:", df.shape)
df.head()

Data awal: (1260, 4)

,judul,link,isi,kategori
0,"Amsal Sitepu Divonis Bebas, Komisi III DPR: Hu...",https://news.detik.com/berita/d-8425590/amsal-...,"Wakil Ketua Komisi III DPR RI, Rano Alfath, me...",Law
1,"Peluncuran Buku ""Teladan Sang Menteri"" Angkat ...",https://www.detik.com/hikmah/khazanah/d-843165...,Akademisi UIN Ar-Raniry Banda Aceh menulis buk...,Education
2,20 Contoh Soal TKA SMP Bahasa Indonesia Plus J...,https://www.detik.com/edu/sekolah/d-8370572/20...,Bahasa Indonesia adalah mata pelajaran wajib y...,Education
3,Polisi Periksa 6 Saksi Kasus Mahasiswa Undip D...,https://www.detik.com/sumut/hukum-dan-kriminal...,Mahasiswa dari Program Studi Antropologi Sosia...,Law
4,Airlangga Rapat Bareng Jokowi Soal Pajak Hibur...,https://news.detik.com/berita/d-7149434/airlan...,Menko Perekonomian Airlangga Hartarto rapat ba...,Economy

## Init NLP

In [4]:
stop_factory = StopWordRemoverFactory()
stopwords = set(stop_factory.get_stop_words())

stem_factory = StemmerFactory()
stemmer = stem_factory.create_stemmer()

## Cleaning (tanpa stopword & stemming dulu)

In [5]:
def clean_text(text):
    if pd.isna(text):
        return ""

    text = text.lower()
    text = re.sub(r"http\S+", " ", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

df["isi_clean_raw"] = df["isi"].apply(clean_text)
df["judul_clean_raw"] = df["judul"].apply(clean_text)

df["text_raw"] = df["judul_clean_raw"] + " " + df["isi_clean_raw"]

df[["judul_clean_raw", "isi_clean_raw", "text_raw"]].head()

,judul_clean_raw,isi_clean_raw,text_raw
0,amsal sitepu divonis bebas komisi iii dpr huku...,wakil ketua komisi iii dpr ri rano alfath meny...,amsal sitepu divonis bebas komisi iii dpr huku...
1,peluncuran buku teladan sang menteri angkat ki...,akademisi uin ar raniry banda aceh menulis buk...,peluncuran buku teladan sang menteri angkat ki...
2,contoh soal tka smp bahasa indonesia plus jawa...,bahasa indonesia adalah mata pelajaran wajib y...,contoh soal tka smp bahasa indonesia plus jawa...
3,polisi periksa saksi kasus mahasiswa undip dis...,mahasiswa dari program studi antropologi sosia...,polisi periksa saksi kasus mahasiswa undip dis...
4,airlangga rapat bareng jokowi soal pajak hiburan,menko perekonomian airlangga hartarto rapat ba...,airlangga rapat bareng jokowi soal pajak hibur...

## Stopword removal

In [6]:
def remove_stopwords(text):
    tokens = text.split()
    tokens = [t for t in tokens if t not in stopwords]
    return " ".join(tokens)

df["text_no_stopword"] = df["text_raw"].apply(remove_stopwords)

df[["text_raw", "text_no_stopword"]].head()

,text_raw,text_no_stopword
0,amsal sitepu divonis bebas komisi iii dpr huku...,amsal sitepu divonis bebas komisi iii dpr huku...
1,peluncuran buku teladan sang menteri angkat ki...,peluncuran buku teladan sang menteri angkat ki...
2,contoh soal tka smp bahasa indonesia plus jawa...,contoh soal tka smp bahasa indonesia plus jawa...
3,polisi periksa saksi kasus mahasiswa undip dis...,polisi periksa saksi kasus mahasiswa undip dis...
4,airlangga rapat bareng jokowi soal pajak hibur...,airlangga rapat bareng jokowi soal pajak hibur...

## Stemming

In [7]:
def stemming(text):
    tokens = text.split()
    tokens = [stemmer.stem(t) for t in tokens]
    return " ".join(tokens)

df["text_stemmed"] = df["text_no_stopword"].apply(stemming)

df[["text_no_stopword", "text_stemmed"]].head()

,text_no_stopword,text_stemmed
0,amsal sitepu divonis bebas komisi iii dpr huku...,amsal sitepu vonis bebas komisi iii dpr hukum ...
1,peluncuran buku teladan sang menteri angkat ki...,luncur buku teladan sang menteri angkat kisah ...
2,contoh soal tka smp bahasa indonesia plus jawa...,contoh soal tka smp bahasa indonesia plus jawa...
3,polisi periksa saksi kasus mahasiswa undip dis...,polisi periksa saksi kasus mahasiswa undip sik...
4,airlangga rapat bareng jokowi soal pajak hibur...,airlangga rapat bareng jokowi soal pajak hibur...

## Final TF-IDF

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)
tfidf_matrix = vectorizer.fit_transform(df["text_stemmed"])

print("TF-IDF shape:", tfidf_matrix.shape)

TF-IDF shape: (1260, 5000)

In [9]:
i = 0  # index sample

print("RAW:\n", df.loc[i, "text_raw"])
print("\nNO STOPWORD:\n", df.loc[i, "text_no_stopword"])
print("\nSTEMMED:\n", df.loc[i, "text_stemmed"])

RAW:
 amsal sitepu divonis bebas komisi iii dpr hukum tak boleh lepas dari realitas wakil ketua komisi iii dpr ri rano alfath menyambut baik vonis bebas amsal christy sitepu oleh pengadilan negeri pn medan dalam kasus korupsi pembuatan video profil desa di kabupaten karo sumatera utara sumut rano menyebut kasus itu menjadi bukti jika hukum tak boleh berjalan kaku dan terlepas dari realitas sosial putusan ini menjadi penegasan bahwa hukum tidak boleh berjalan secara kaku dan terlepas dari realitas sosial apa yang diputuskan oleh majelis hakim hari ini mencerminkan sensitivitas terhadap rasa keadilan publik khususnya bagi para pekerja kreatif yang selama ini kerap berada di wilayah abu abu dalam penilaian hukum kata rano kepada wartawan rabu rano menyebut dari perspektif hukum pidana pasal pasal tindak pidana korupsi khususnya pasal uu tipikor tak dapat dilepaskan dari pembuktian unsur penyalahgunaan kewenangan dan adanya niat jahat mens rea dalam perkara ini lanjutnya penting untuk melihat apakah benar terdapat intensi untuk merugikan keuangan negara scroll to continue with content atau justru terjadi perbedaan penilaian atas jasa profesional yang secara karakteristik memang tidak memiliki standar harga baku penegakan hukum pidana tidak cukup hanya bertumpu pada selisih angka atau konstruksi kerugian negara semata ujar legislator pkb ini harus ada pembuktian yang utuh terhadap unsur kesalahan termasuk niat jahat dan penyalahgunaan kewenangan jika aspek tersebut tidak terpenuhi maka pemaksaan penggunaan instrumen pidana justru berpotensi menimbulkan ketidakadilan sambungnya ia juga menyoroti pentingnya kehati hatian dalam menggunakan hasil audit kerugian negara sebagai dasar pembuktian terutama dalam sektor yang berbasis kreativitas menurutnya pendekatan yang menilai komponen ide editing maupun proses kreatif lainnya sebagai nol menunjukkan adanya kekeliruan dalam memahami objek yang dinilai dalam hukum kita mengenal bahwa tidak semua kerugian yang dihitung secara administratif dapat serta merta dikualifikasikan sebagai kerugian negara dalam konteks pidana apalagi jika objeknya adalah kerja kreatif yang mengandung nilai subjektif dan berbasis kesepakatan para pihak lanjutnya rano menilai perkara ini menjadi momentum penting untuk menunjukkan bahwa negara hadir memberikan pengakuan terhadap nilai kerja kreatif anak muda ia menyebut pendekatan yang menyamakan kerja kreatif dengan logika pengadaan barang semata keliru adanya kerja kreatif tidak bisa diukur hanya dengan parameter material di dalamnya ada ide proses berpikir pengalaman dan keahlian yang dibangun bertahun tahun itu semua memiliki nilai yang tidak bisa dipukul rata atau bahkan diabaikan tambahnya lebih jauh rano juga menyoroti relevansi putusan ini di tengah perkembangan teknologi termasuk pesatnya kecerdasan buatan ai menurutnya justru di era seperti saat ini orisinalitas dan kreativitas manusia menjadi semakin bernilai dan harus dilindungi oleh sistem hukum di tengah kemajuan ai kita harus semakin sadar bahwa otak manusia dengan orisinalitasnya tidak tergantikan justru di situlah letak nilai utama dari karya kreatif negara harus hadir untuk melindungi dan menghargai nilai tersebut bukan sebaliknya ujarnya sebelumnya hakim pengadilan negeri pn medan menyatakan amsal christy sitepu tidak bersalah dalam kasus kasus korupsi pembuatan video profil desa di kabupaten karo sumut amsal pun divonis bebas menyatakan terdakwa amsal tidak terbukti bersalah dan divonis bebas kata majelis hakim m yusafrihardi girsang saat membacakan amar putusan di pn medan dilansir detiksumut rabu amsal sebelumnya dituntut hukuman tahun penjara oleh jaksa selain itu amsal dituntut membayar denda dan uang pengganti menuntut menjatuhkan pidana kepada terdakwa amsal sitepu oleh karena itu tahun penjara ucap jpu wira arizona di pn medan jumat lihat video amsal sitepu divonis bebas komisi iii jangan mudah mengkriminalisasi gambas video detik

NO STOPWORD:
 amsal sitepu divonis bebas komisi iii dpr hukum tak lepas realitas wakil ketua komisi iii dpr ri rano alfath menyambut baik vonis bebas amsal christy sitepu pengadilan negeri pn medan kasus korupsi pembuatan video profil desa kabupaten karo sumatera utara sumut rano menyebut kasus menjadi bukti hukum tak berjalan kaku terlepas realitas sosial putusan menjadi penegasan hukum berjalan kaku terlepas realitas sosial apa diputuskan majelis hakim hari mencerminkan sensitivitas rasa keadilan publik khususnya pekerja kreatif selama kerap berada wilayah abu abu penilaian hukum kata rano wartawan rabu rano menyebut perspektif hukum pidana pasal pasal tindak pidana korupsi khususnya pasal uu tipikor tak dilepaskan pembuktian unsur penyalahgunaan kewenangan adanya niat jahat mens rea perkara lanjutnya penting melihat benar terdapat intensi merugikan keuangan negara scroll to continue with content justru terjadi perbedaan penilaian atas jasa profesional karakteristik memang memiliki standar harga baku penegakan hukum pidana cukup bertumpu selisih angka konstruksi kerugian negara semata ujar legislator pkb pembuktian utuh unsur kesalahan termasuk niat jahat penyalahgunaan kewenangan aspek tersebut terpenuhi pemaksaan penggunaan instrumen pidana justru berpotensi menimbulkan ketidakadilan sambungnya menyoroti pentingnya kehati hatian menggunakan hasil audit kerugian negara dasar pembuktian terutama sektor berbasis kreativitas menurutnya pendekatan menilai komponen ide editing maupun proses kreatif lainnya nol menunjukkan adanya kekeliruan memahami objek dinilai hukum mengenal semua kerugian dihitung administratif merta dikualifikasikan kerugian negara konteks pidana objeknya kerja kreatif mengandung nilai subjektif berbasis kesepakatan pihak lanjutnya rano menilai perkara menjadi momentum penting menunjukkan negara hadir memberikan pengakuan nilai kerja kreatif anak muda menyebut pendekatan menyamakan kerja kreatif logika pengadaan barang semata keliru adanya kerja kreatif diukur parameter material dalamnya ide proses berpikir pengalaman keahlian dibangun bertahun tahun semua memiliki nilai dipukul rata bahkan diabaikan tambahnya lebih jauh rano menyoroti relevansi putusan tengah perkembangan teknologi termasuk pesatnya kecerdasan buatan ai menurutnya justru era orisinalitas kreativitas manusia menjadi semakin bernilai dilindungi sistem hukum tengah kemajuan ai semakin sadar otak manusia orisinalitasnya tergantikan justru situlah letak nilai utama karya kreatif negara hadir melindungi menghargai nilai tersebut bukan sebaliknya ujarnya sebelumnya hakim pengadilan negeri pn medan menyatakan amsal christy sitepu bersalah kasus kasus korupsi pembuatan video profil desa kabupaten karo sumut amsal divonis bebas menyatakan terdakwa amsal terbukti bersalah divonis bebas kata majelis hakim m yusafrihardi girsang membacakan amar putusan pn medan dilansir detiksumut rabu amsal sebelumnya dituntut hukuman tahun penjara jaksa amsal dituntut membayar denda uang pengganti menuntut menjatuhkan pidana terdakwa amsal sitepu tahun penjara ucap jpu wira arizona pn medan jumat lihat video amsal sitepu divonis bebas komisi iii jangan mudah mengkriminalisasi gambas video detik

STEMMED:
 amsal sitepu vonis bebas komisi iii dpr hukum tak lepas realitas wakil ketua komisi iii dpr ri rano alfath sambut baik vonis bebas amsal christy sitepu adil negeri pn medan kasus korupsi buat video profil desa kabupaten karo sumatera utara sumut rano sebut kasus jadi bukti hukum tak jalan kaku lepas realitas sosial putus jadi tegas hukum jalan kaku lepas realitas sosial apa putus majelis hakim hari cermin sensitivitas rasa adil publik khusus kerja kreatif lama kerap ada wilayah abu abu nilai hukum kata rano wartawan rabu rano sebut perspektif hukum pidana pasal pasal tindak pidana korupsi khusus pasal uu tipikor tak lepas bukti unsur penyalahgunaan wenang ada niat jahat mens rea perkara lanjut penting lihat benar dapat intensi rugi uang negara scroll to continue with content justru jadi beda nilai atas jasa profesional karakteristik memang milik standar harga baku tega hukum pidana cukup tumpu selisih angka konstruksi rugi negara semata ujar legislator pkb bukti utuh unsur salah masuk niat jahat penyalahgunaan wenang aspek sebut penuh paksa guna instrumen pidana justru potensi timbul ketidakadilan sambung sorot penting hati hati guna hasil audit rugi negara dasar bukti utama sektor bas kreativitas turut dekat nilai komponen ide editing maupun proses kreatif lain nol tunjuk ada keliru paham objek nilai hukum kenal semua rugi hitung administratif merta kualifikasi rugi negara konteks pidana objek kerja kreatif kandung nilai subjektif bas sepakat pihak lanjut rano nilai perkara jadi momentum penting tunjuk negara hadir beri aku nilai kerja kreatif anak muda sebut dekat sama kerja kreatif logika ada barang semata keliru ada kerja kreatif ukur parameter material dalam ide proses pikir alam ahli bangun tahun tahun semua milik nilai pukul rata bahkan abai tambah lebih jauh rano sorot relevansi putus tengah kembang teknologi masuk pesat cerdas buat ai turut justru era orisinalitas kreativitas manusia jadi makin nila lindung sistem hukum tengah maju ai makin sadar otak manusia orisinalitas ganti justru situ letak nilai utama karya kreatif negara hadir lindung harga nilai sebut bukan balik ujar belum hakim adil negeri pn medan nyata amsal christy sitepu salah kasus kasus korupsi buat video profil desa kabupaten karo sumut amsal vonis bebas nyata dakwa amsal bukti salah vonis bebas kata majelis hakim m yusafrihardi girsang baca amar putus pn medan lansir detiksumut rabu amsal belum tuntut hukum tahun penjara jaksa amsal tuntut bayar denda uang ganti tuntut jatuh pidana dakwa amsal sitepu tahun penjara ucap jpu wira arizona pn medan jumat lihat video amsal sitepu vonis bebas komisi iii jangan mudah kriminalisasi gambas video detik

In [10]:
import pickle

# =========================
# 1. SIMPAN METADATA (tanpa vector)
# =========================
df[["judul", "isi", "link", "kategori", "text_stemmed"]].to_csv(
    "/kaggle/working/articles_metadata.csv",
    index=False
)

# =========================
# 2. SIMPAN TF-IDF MATRIX (SPARSE)
# =========================
with open("/kaggle/working/tfidf_matrix.pkl", "wb") as f:
    pickle.dump(tfidf_matrix, f)

# =========================
# 3. SIMPAN VECTORizer
# =========================
with open("/kaggle/working/tfidf_vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

# =========================
# 4. (OPSIONAL) SIMPAN DATAFRAME FINAL
# =========================
df.to_csv("/kaggle/working/dataset_full_preprocessed.csv", index=False)

print("✅ Semua file berhasil disimpan di /kaggle/working/")

✅ Semua file berhasil disimpan di /kaggle/working/